[package]
name = "oracles"
version = "0.1.0"
authors = ["Evgeny Ukhanov <mrlsd@ya.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
