build:
	@cargo build --target wasm32-unknown-unknown --release
	
wat:
	@wasm2wat target/wasm32-unknown-unknown/release/xpx_supercontracts_example_oracles.wasm -o ~/xpx_supercontracts_example_oracles.wat